masterに対してpull requestを送っていたので、developに対してpull requestをまた送ることにしました。
morinoparty/MorinoInsect pull request #10
Opened 2021-03-03 10:22 UTC by sota70

2021-03-03 10:24 UTC, sota70 commented
developに対して送りなおしたついでに、システムの続きを作っておきました

2021-03-04 07:32 UTC, NamiUni requested changes
またbuild.gradleが入ってしまっています。あと、機能追加のブランチは feature/機能名など で作成し、マージが完了したら再利用しないようお願いします。

2021-03-04 07:32 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +    private val WalkCount = mutableMapOf<Player, Int>()
なぜPascalCase？

2021-03-04 07:32 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +            val walkCount = WalkCount[player]!! + 1
kotlinはnull安全に書かれた言語です。!!演算子はぬるぽの原因になるのでどうしても必要な時だけ使用するようお願いします。できるだけnullチェックをお願いします。

2021-03-04 07:32 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/IInsectSpawnable.kt
> +    var Tier: InsectTier
ここもなぜPascalCase？あと値が変わると困るから定数でいいのでは？

2021-03-04 10:02 UTC, Yahirrro commented
@sota70 
PR名は、作業に関係する対するタイトルにしてほしい

2021-03-04 10:31 UTC, sota70 commented
あ、了解です。直しておきます

2021-03-27 04:53 UTC, NamiUni commented
別なブランチでやり直してるので閉じます

2021-03-27 04:53 UTC, closed without merging