✨ 虫のスポーン処理を作成しました
morinoparty/MorinoInsect pull request #16
Opened 2021-03-13 03:39 UTC by sota70

## issue番号

## やったこと

- IInsectBaseというinterfaceのspawnメソッドに虫のスポーン処理を書き加えた。
- コンフィグの更新に合わせてIInsectBaseのプロパティを新しくした
- extentionsというパッケージの中にCollectionの中からランダムに要素を取り出す拡張関数を作った

## やらないこと

- なし 

## 動作確認

- 動作確認の方法がまだ分からないのでやってないです

## その他

2021-03-13 07:01 UTC, Yahirrro requested changes
build.gradle.ktsが消えている
修正が必要

2021-03-13 08:15 UTC, NamiUni approved these changes
issue番号は#で書けばissueへのリンクが作成されます。
メソッド名に関してはここが参考になります。https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6
この間も言いましたがファイル構成はmore-fishを参考にしてください。パッケージ構成やクラス設計など全体的にわかりやすく設計されています。
今developブランチへマージするとfeature/configブランチと大きく競合する可能性があるので待った方がいいかもです。

2021-03-13 08:15 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +}
クラス名に複数形を用いると変数名がややこしくなる可能性があるから使用しない方がいいと思うんだけどどうだろう

2021-03-13 09:02 UTC, NamiUni commented
動作確認はローカルでpaperサーバーを立ててプラグインを実行してください

2021-03-13 10:45 UTC, sota70 commented on build.gradle.kts
> -}
ごめん、、、

2021-03-13 10:47 UTC, sota70 commented on src/main/kotlin/com/github/morinoparty/morinoinsect/MorinoInsect.kt
> +    }
知らなかったです、ありがとうございます

2021-03-13 14:04 UTC, sota70 commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/IInsectBase.kt
> +interface IInsectBase {
https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/interfaces/
どうやらc#のコーディング規約のものだったようです。
kotlinでは関係ないですね！

2021-03-13 14:29 UTC, sota70 commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/IInsectBase.kt
> +interface IInsectBase {
一応Iを名前から外しておきました

2021-03-13 14:30 UTC, sota70 commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +}
ちなみにこれはクラスではなくて拡張関数です。
MutableListに拡張関数としてselectRandomlyという関数を追加しています。
appropriateBlocksは変数名ですね

2021-03-15 14:21 UTC, NamiUni requested changes
相変わらずブランチの内容と関係のない内容がコミットされています。dokkaはブランチを分ける必要があります。
親切に追加してくれるのはありがたいのですが、ビルドスクリプトの書き方をよく理解できていないのであればまずある程度理解してから追加をお願いします。`plugins`ブロックと`apply plugin`はどちらもGradleプラグインの適用メソッドであり、二つとも書く必要はありません。そして`apply plugin`は古いメソッドですので使用は推奨されていません。

2021-03-15 14:21 UTC, NamiUni commented on build.gradle.kts
> +    id("org.jetbrains.dokka") version "1.4.20"
この一文だけでいい

2021-03-15 14:21 UTC, NamiUni commented on build.gradle.kts
> +
不要

2021-03-15 14:21 UTC, NamiUni commented on build.gradle.kts
> +
不要

2021-03-15 14:21 UTC, NamiUni commented on build.gradle.kts
> +    testImplementation("junit:junit:4.12")
不要だしkotlinに関しては`plugins`で導入済み`kotlin("jvm") version "1.4.30"`

2021-03-15 14:21 UTC, NamiUni commented on build.gradle.kts
> +
不要

2021-03-15 23:50 UTC, sota70 commented on build.gradle.kts
> +
ここの部分に関してはdokkaのデフォルトでpublic以外のメソッドや変数を含まない設定だったので、それを変えるために書きました。なのでここは消さなくても大丈夫だと思います！

2021-03-16 04:09 UTC, NamiUni commented on build.gradle.kts
> +
スタイルガイドではKDocは全ての`public`及び`protected`なメソッドで書く必要がありますが、それ以外では必須ではありません。`private`なメソッドでも書くべきかどうかを先に決める必要があります。

2021-03-16 05:33 UTC, sota70 commented on .commit_template
> +# ♻     :recycle: リファクタリング
それに関しては良く分からないです（）

2021-03-16 05:33 UTC, sota70 commented
今度ミーティングでドキュメンテーションコメントについて話し合いますか！

2021-03-16 05:48 UTC, sota70 commented on .commit_template
> +# ♻     :recycle: リファクタリング
直しておきます、すみません

2021-03-16 05:50 UTC, sota70 commented
僕のミスでresourcesフォルダー消しちゃったので、作り直したんですが、なぜか変更点もないはずなのに変更点があるから再度コミットしろとか言われてコミットせざるを得なかったので、コミットしました

2021-03-24 11:30 UTC, Yahirrro commented
@sota70 コードスタイルにエラーが出ています。修正してください。

2021-03-29 03:48 UTC, NamiUni requested changes
変更点多数。ドキュメントはパブリックなメソッドにのみ書いてください。

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +    private val appropriateBlocks: MutableList<Block> = ArrayList()
ArrayList()じゃなくてmutableListOf()でいい

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/SpawningInsectsListener.kt
> +    }
虫をスポーンさせる条件は「プレイヤーが30歩歩いたら」ではなくて「プレイヤーが虫取り網を持って右クリックしたら」です

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/condition/Condition.kt
> +}
こっちで書いたので不要

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/InsectBase.kt
> +}
ここも不要

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/InsectTier.kt
> +}
不要

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/InsectTierManager.kt
> +}
不要

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/InsectsManager.kt
> +}
不要

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/insectslist/NullInsect.kt
> +}
ここも不要になる

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/AreaCordinates.kt
> +data class AreaCordinates(val x: Int, val y: Int)
Utilパッケージは虫取りプラグイン全体で使用する可能性があり、なおかつどこにいれればいいかわからないものを入れてください。座標関係は虫取り時にしか使わないのでCatchingパッケージに新しくパッケージを作るなりした方がいいです。

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/Vector.kt
> +)
これもここのパッケージではない

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/areaChecker.kt
> +}
これも

2021-03-29 03:48 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/condition/SpawnTypeCondition.kt
> +}
これも不要かな

2021-04-01 06:30 UTC, NamiUni requested changes
シングルトンが本当に必要かどうか考慮する必要がある。リターン忘れあり

2021-04-01 06:30 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/area/AreaChecker.kt
> +                leftDownCorner[i].x == x && leftDownCorner[i].y == y
return が抜けてる

2021-04-01 06:30 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/area/AreaChecker.kt
> +    companion object {
シングルトンである理由がわからない。

2021-04-16 00:42 UTC, NamiUni commented
最近クラスの名前の付け方を色々と調べてたんだけど、リスナークラスの名前は発生したイベントの名前を付けるべきみたい。だから`SpawningInsectsListener`は虫が発生している最中のイベントを監視するクラスという意味になっちゃうから不適切になる。 「虫あみを右クリックした事をリッスンするクラス」という意味で`NetRightClickListener`みたいな名前にしたほうが良さげ。メソッドもコールバックメソッドになるので`onSpawn`だとスポーンした時に実行するメソッドって意味になっちゃう。イベント名をメソッド名にそのまま使って`onPlayerInteract`にするのがいいね
http://www.kab-studio.biz/Programing/JavaA2Z/Word/00000422.html
https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6

2021-04-17 07:59 UTC, NamiUni submitted a review, later dismissed

2021-04-17 08:26 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/area/SpawnLocationAdjuster.kt
> +interface SpawnLocationAdjuster {
あとで多分移動するからこのままで構わないんだけど、これがインターフェースなのってどんな理由があるの？

2021-04-25 02:50 UTC, NamiUni commented
#35に含めちゃったので閉じます。変更点などがあれば #35にプルリクエストを送るか#35を直接変更してください

2021-04-25 02:50 UTC, closed without merging