:+1: Fix Thread.sleep() -> waitFor()
morinoparty/MorinoInsect pull request #2
Opened 2021-02-28 10:40 UTC by sota70

秒数をカウントするメソッドを使えるものに書き換えました

2021-03-01 07:16 UTC, Yahirrro commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/Net.kt
> +class Net {
Netだと抽象度が高いので、InsectCatchingNetのように具体度をあげてほしい
Net だと InternetやNetworkを想像しやすい

2021-03-01 07:17 UTC, Yahirrro commented
@NamiUni Reviewお願い

2021-03-01 07:18 UTC, Yahirrro requested changes
クラス名Netをより抽象度の高い関数名へ変更して欲しい

2021-03-02 03:31 UTC, NamiUni requested changes
コードの内容は問題ないです。スタイルガイドに従って指定箇所の変更をお願いします。

2021-03-02 03:31 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/util/InsectCatchingNet.kt
> +            net.itemMeta                  = itemMeta
ここも

2021-03-02 03:31 UTC, NamiUni commented on src/main/kotlin/com/github/morinoparty/morinoinsect/catching/CatchingListener.kt
> +class CatchInsectsEvent(private val plugin : MorinoInsect) : Listener {
コロン : の前に入れる空白文字は基本クラスまたはインターフェースを指定する目的でクラス宣言で使用する場合などに限ります。なのでクラスや関数のプロパティ、及び変数の型宣言で入れる必要はありません。

2021-03-02 03:50 UTC, NamiUni approved these changes

2021-03-02 08:13 UTC, Yahirrro approved these changes
👍

2021-03-02 08:13 UTC, merged